### ISSUE TITLE
Namespaces get removed when exporting foreign diagram

### ISSUE THREAD

**Issue by linus-amg** [bpmn-io/bpmn-js#1310]
__Describe the Bug__

A diagram I exported from a different Modeler and afterwards imported into bpmn-js is not schema valid anymore as soon as I export it from bpmn-js.

This issue is coming from running tests for the upcoming bpmn miwg demo.

__Fixtures__
[Advertise a job vacancy.original.edit.bpmn.zip](https://github.com/bpmn-io/bpmn-js/files/4458373/Advertise.a.job.vacancy.original.edit.bpmn.zip)

__Steps to Reproduce__

1. Have a look at the attached xml and see that `xmlns:dc`, `xmlns:di` and `xmlns:bpmndi` are part of `<defintions>`
2. Import attached XML into a bpmn-js instance
2. use the `saveXML` method of the bpmn-js instance to get the xml
3. see that the `xmlns:dc`, `xmlns:di` and `xmlns:bpmndi` attributes are not present in the definitions anymore

I tried to create a showcase: https://codesandbox.io/s/busy-dawn-eel38?file=/src/index.js just have a look at the console tab to see the different attributes before and after import+export.

__Expected Behavior__

I expected the 3 mentioned namespaces to still be inside definitions, so importing and exporting this model which was created in a different modeler is still schema-valid.

__Impact__
It's a blocker for the bpmn miwg demo because we cannot import models from CaseAgile and export them, to make the roundtrip.

__Environment__
 - OS: Linux, MacOS
 - Library version: 6.4.1
Also tried Camunda Modeler 3.7, 4 and Cawemo and results are the same.

**Comment by nikku** [comment]
Added basic reproducible test cases in [bpmn-moddle](https://github.com/bpmn-io/bpmn-moddle/commit/a36fa0ab03c0ef22a003b7336590b6984c2bee80) as well as [moddle-xml](https://github.com/bpmn-io/moddle-xml/commit/e1af6c47a938de90380abd9be4c07d9c4b97320b).

We'll look into this.

Our tools should not ever export invalid XML, no matter how cryptic / special the input XML is.

**Comment by falko** [comment]
@nikku thank you for looking into this!

**Comment by falko** [comment]
When trying to root cause this, I made an observation:
The attached BPMN file uses elements from the BPMN semantic namespace without a namespace prefix and correctly declares that namespace using `xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"` on the `definitions` root element. So that looks fine.
In addition, it defines the prefix `semantic` for the same namespace through `xmlns:semantic="http://www.omg.org/spec/BPMN/20100524/MODEL"` but never uses it. Technically that's useless but not invalid. However, we start using that prefix when we export that file. While that's also not invalid, such behavior could lead to problems for people who work with branching and merging, e.g. in Git, because almost every line of the file is changed.

Removing the unused namespace `semantic` prefix makes the modeler keep the unprefixed elements. However, it does not fix the issue of the missing `bpmndi`, `di`, and `dc` namespace prefix declarations. So maybe this observation is even a separate issue.

**Comment by nikku** [comment]
I've already root caused these things, too.

See linked, focussed test cases attached.

Regarding the namespaces and the specific example, what namespace exports would you expect?

```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<definitions id="Definitions" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" targetNamespace="http://bpmn.io">
  <BPMNDiagram id="BPMNDiagram_1" xmlns="http://www.omg.org/spec/BPMN/20100524/DI">
    <BPMNPlane bpmnElement="Definitions" xmlns="http://www.omg.org/spec/BPMN/20100524/DI" />
  </BPMNDiagram>
</definitions> 
```

**Comment by nikku** [comment]
> In addition, it defines the prefix semantic for the same namespace through xmlns:semantic="http://www.omg.org/spec/BPMN/20100524/MODEL" but never uses it. Technically that's useless but not invalid. However, we start using that prefix when we export that file. While that's also not invalid, such behavior could lead to problems for people who work with branching and merging, e.g. in Git, because almost every line of the file is changed.

As you mentioned, this is a different issue.

**Comment by falko** [comment]
> Regarding the namespaces and the specific example, what namespace exports would you expect?

The namespaces that are used in the model. In particular, the namespace prefixes `bpmndi`, `di`, and `dc` were undeclared. Schema validation can be used to verify.

**Comment by nikku** [comment]
So the export would look as imported?

```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<definitions id="Definitions" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" targetNamespace="http://bpmn.io">
  <BPMNDiagram id="BPMNDiagram_1" xmlns="http://www.omg.org/spec/BPMN/20100524/DI">
    <BPMNPlane bpmnElement="Definitions" xmlns="http://www.omg.org/spec/BPMN/20100524/DI" />
  </BPMNDiagram>
</definitions> 
```

Or should it drop the unused / not needed `bpmndi` namespace?

```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<definitions id="Definitions" xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" targetNamespace="http://bpmn.io">
  <BPMNDiagram id="BPMNDiagram_1" xmlns="http://www.omg.org/spec/BPMN/20100524/DI">
    <BPMNPlane bpmnElement="Definitions" xmlns="http://www.omg.org/spec/BPMN/20100524/DI" />
  </BPMNDiagram>
</definitions> 
```

**Comment by falko** [comment]
Ideally, it looks like the imported: no namespace prefixes but `xmlns` attributes on elements. A bonus would be to remove unused namespace declarations.

If it is too hard to remember if the DI elements were prefixed or not, we could also export them allways with prefix but also declare it properly.

**Comment by nikku** [comment]
Thanks! Your feedback helps to move towards a usable solution.

**Comment by falko** [comment]
Just a thought: Maybe filtering out unused namespace prefix declaration before the import could help to focus on the right prefixes to remember for the export.

**Comment by nikku** [comment]
> Just a thought: Maybe filtering out unused namespace prefix declaration before the import could help to focus on the right prefixes to remember for the export.

This is an implementation detail we don't have to care about at this point. What is more important is the what and you've helped us tremendously setting that straight.

When it comes to fixing this bug: We've queued it into our "tasks to work on" topic list. We do not have any concrete plans when it will be fixed.

**Comment by falko** [comment]
If you can not fix it any time soon, what could be a workaround, i.e. what could we ask CaseAgile to change in their export? Would it help if their tool would prefix the DI elements? It could save some file size, given how often the `xmlns` attribute has to be put in the DI section of the XML.

**Comment by nikku** [comment]
What is your time line, i.e. when would you need a fix.

We'll not fix this _right now_ but we'll look into this in an orderly manner, in the near future.

**Comment by nikku** [comment]
CaseAgile could export their diagrams in the normal manner:

```xml
<definitions xmlns:bpmndi="...">
  <bpmndi:BPMNDiagram>...</bpmndi:BPMNDiagram>
</definitions>
```

Rather than attaching the namespace on each element indivually _AND_ writing the `xmlns:bpmndi` namespace information:


```xml
<definitions xmlns:bpmndi="...">
  <BPMNDiagram xmlns="...">...</bpmndi:BPMNDiagram>
</definitions>
```

But it is really a bug on our side we need to fix, too.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/bpmn-js/commit/3fac7071e1ff343d1b90c1e469c6385c3cbf1035.

**Comment by nikku** [comment]
Released with `v6.4.2`.

**Comment by nikku** [comment]
What we've implemented:

* We keep and use namespaces as imported but cleanup unused namespaces, too. Cf. https://github.com/bpmn-io/bpmn-js/issues/1310#issuecomment-613020268, option :two:.

**Comment by falko** [comment]
Wow @nikku! That was fast. Does released mean that I can test it on http://demo.bpmn.io?

**Comment by nikku** [comment]
Yes.

**Comment by falko** [comment]
It is better but not completely fixed:

1. ` BPMNLabel` still has prefixed `dc:Bounds` children
2. `di:waypoint` are still prefixed with an undefined prefix
3. Not a blocker but still worth mentioning: the order of elements seems to have changed a lot both in semantic and DI.

**Comment by nikku** [comment]
We have to fix

**Comment by nikku** [comment]
...(1) and (2).

**Comment by ChrisSchoe** [comment]
Just fyi, we'd also be interested in an eventual fix for this issue. Our viadee BPMN modeler for Confluence also uses bpmn-js and it'd make our participation in the miwg demo much easier.

**Comment by oguzeroglu** [comment]
We're working on a fix and planning to merge the fix within this week.

**Comment by oguzeroglu** [comment]
Closed via #1317

**Comment by falko** [comment]
Awesome! Thank you!
